### PR TITLE
Dev/updates

### PR DESCRIPTION
**Pull request by devagrawal09**
Made minor updates
- Spinners for each step for better observability
- File name can be passed as an argument
- OFFSET to skip users that have already been migrated
- Renamed DELAY and RETRY_DELAY to DELAY_MS and RETRY_DELAY_MS

Console output showing new enhancements
image

### CODE REVIEW

**Review by JacobMGEvans — APPROVED** [review]
Love this offset idea!!!

**Comment by royanger** [comment]
Hey @devagrawal09 -- let's not do a new line for each user. I don't think that's super useful.

```
// before starting
const length = users.length
let current = 1
const spinner = ora(`Migrating users`).start();
spinner.color = 'cyan';
spinner.spinner = "dots8Bit"

// inside of the function, etc
// count errors
spinner.text = `Migrating users: ${current}/${length}`;
current++

// when done
// also display errors
spinner.stopAndPersist({
  text: "Users migrated",
  symbol: logSymbols.success
})
spinner.stop()

```

**Comment by JacobMGEvans** [comment]
> Hey @devagrawal09 -- let's not do a new line for each user. I don't think that's super useful.
> 
> ```
> // before starting
> const length = users.length
> let current = 1
> const spinner = ora(`Migrating users`).start();
> spinner.color = 'cyan';
> spinner.spinner = "dots8Bit"
> 
> // inside of the function, etc
> // count errors
> spinner.text = `Migrating users: ${current}/${length}`;
> current++
> 
> // when done
> // also display errors
> spinner.stopAndPersist({
>   text: "Users migrated",
>   symbol: logSymbols.success
> })
> spinner.stop()
> ```

Yeah lets update the previous number rather than a new `stdout`

**Comment by devagrawal09** [comment]
How's it now
https://github.com/clerk/migration-script/assets/19648701/f50950e5-244b-483a-8ecb-21c27987b539

**Comment by JacobMGEvans** [comment]
> How's it now https://github.com/clerk/migration-script/assets/19648701/f50950e5-244b-483a-8ecb-21c27987b539

not a huge fan of the flickering cooldown text. Besides that it looks good. I am merging so it can be iterated on.

**Pull request merged**
